image: openjdk:11

before_script:
  - apt-get update -yqq
  - apt-get install ant ivy -yqq

php-pdftk:
  stage: test
  script:
    - ant -lib /usr/share/java
    - echo -e '#!/bin/bash\njava -cp build/jar/pdftk.jar:lib/bcprov-1.58.jar:lib/commons-lang3.jar pdftk "$@"' > /usr/bin/pdftk
    - chmod +x /usr/bin/pdftk
    - pdftk --version
    - apt-get install phpunit composer -yqq
    - git clone https://github.com/mikehaertl/php-pdftk
    - cd php-pdftk
    - composer install
    - phpunit
