.ant-job:
  stage: test
  except:
    variables:
      - $WEB_JOB != null
  image: openjdk:11
  before_script:
  - apt-get update -yqq
  - apt-get install ant ivy -yqq

php-pdftk:
  extends: .ant-job
  script:
    - ant -lib /usr/share/java
    - echo -e '#!/bin/bash\njava -cp' `pwd`'/build/jar/pdftk.jar:'`pwd`'/lib/bcprov-jdk15on-1.64.jar:'`pwd`'/lib/commons-lang3-3.9.jar com.gitlab.pdftk_java.pdftk "$@"' > /usr/bin/pdftk
    - chmod +x /usr/bin/pdftk
    - apt-get install php-mbstring phpunit composer -yqq
    - git clone --depth 1 https://github.com/marcvinyals/php-pdftk
    - cd php-pdftk
    - composer install
    - pdftk --version
    - phpunit

test:
  extends: .ant-job
  script:
    - apt-get install poppler-utils -yqq
    - ant -lib /usr/share/java test-resolve
    - ant -lib /usr/share/java -lib ./lib test
    - perl -ne 'm/Total.*?([0-9]{1,3})%/; print "Coverage $1%\n"' coverage/index.html
  artifacts:
    paths:
      - coverage/

pages:
  only:
    - master
  stage: deploy
  dependencies:
    - test
  script:
    - mkdir public/
    - mv coverage/ public/
  artifacts:
    paths:
      - public/

.gradle-job:
  only:
    - tags
  stage: deploy
  image: gradle:latest
  variables:
    GRADLE_VERSION: "6.7.1"
  script:
    - gradle wrapper --gradle-version=$GRADLE_VERSION
    - ./gradlew shadowJar
    - java -jar build/libs/pdftk-all.jar --version

gradle:
  extends: .gradle-job
  artifacts:
    paths:
      - build/libs/pdftk-all.jar

gradle-5.0:
  extends: .gradle-job
  variables:
    GRADLE_VERSION: "5.0"

gradle-web:
  extends: .gradle-job
  stage: test
  only:
    variables:
      - $CI_PIPELINE_SOURCE == "web" && $WEB_JOB == "gradle"
  artifacts:
    paths:
      - build/libs/pdftk-all.jar
    expire_in: 1 month

spotless:
  stage: test
  except:
    variables:
      - $WEB_JOB != null
  image: gradle:latest
  script:
    - gradle spotlessCheck

nativeimage:
  only:
    - tags
  stage: deploy
  # cf https://gitlab.com/pdftk-java/pdftk/-/issues/68 before updating
  image: oracle/graalvm-ce:20.1.0-java11
  before_script:
    - gu install native-image
    - yum install -y wget unzip
    - wget https://services.gradle.org/distributions/gradle-6.7.1-bin.zip
    - unzip gradle-6.7.1-bin.zip
  script:
    - ./gradle-6.7.1/bin/gradle nativeImage
    - ./build/native-image/pdftk --version
  artifacts:
    paths:
      - build/native-image/pdftk

nativeimage-web:
  extends: nativeimage
  stage: test
  only:
    variables:
      - $CI_PIPELINE_SOURCE == "web" && $WEB_JOB == "nativeimage"
  script:
    - ./gradle-6.7.1/bin/gradle -Pgeneratedebuginfo=1 nativeImage
    - ./build/native-image/pdftk --version
  artifacts:
    paths:
      - build/native-image/pdftk
    expire_in: 1 month
